export const projects = [
  {
    title: '한수원 ERP 고도화',
    duration: '2023.02 ~ 2024.02',
    size: '130명 이상',
    work: '단위업무시스템 개발, 프로젝트 사업 관리',
    desc: '경영관리분야 BSC 성과지표 시스템 개발',
    stack: ['넥사크로', 'iBatis', 'P6'],
    bg: 'rgb(226 232 240)',
    bg2: 'rgb(209, 250, 229)',
    tc: 'inherit',
    link: {
      github: null,
      web: null,
    },
    image: '/khnp.svg',
  },
  {
    title: '우만시',
    duration: '2023.07 ~ 2023.08',
    size: '4명',
    work: '백엔드, 프론트(회원가입 이메일 인증)',
    desc: '추억 공유 서비스 개발',
    stack: ['Spring', 'Redis', 'Nginx', 'React'],
    bg: 'rgb(148, 163, 184)',
    bg2: '#f4eeff',
    tc: 'inherit',
    link: {
      github: 'https://github.com/mrbonk97/jyck',
      web: null,
    },
    image: '/our-memory.svg',
  },
  {
    title: '공유',
    duration: '2024.03 ~ 2024.04',
    size: '1명',
    work: '백엔드, 프론트',
    desc: '파일 공유 서비스',
    stack: ['Spring Boot', 'Nextjs'],
    bg: 'rgb(51, 65, 85)',
    bg2: 'rgb(255, 255, 255)',
    tc: 'white',
    link: {
      github: 'https://github.com/mrbonk97/file-share-client',
      web: 'https://github.com/mrbonk97/file-share-client',
    },
    image: '/0u.png',
  },
  {
    title: '피어',
    duration: '2024.04 ~ 2023.05',
    size: '5명',
    work: '프론트',
    desc: '프로젝트 상담 서비스',
    stack: ['Nextjs'],
    bg: 'inherit',
    bg2: '#fda058',
    tc: 'inherit',
    link: {
      github: 'https://github.com/swyp-peer/peer-client',
      web: 'https://github.com/mrbonk97/file-share-client',
    },
    image: '/peer.png',
  },
];
