"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Antoniv (https://sketchfab.com/antoniv3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tung-tung-tung-sahur-lowpoly-version-f20de67ce7dc457d87ff050ad5e9b162
Title: Tung Tung Tung Sahur (Lowpoly version)
*/

import { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import type { Group } from "three";
import * as THREE from "three";

export function Model() {
  const groupRef = useRef<Group | null>(null);

  const { nodes, materials } = useGLTF("/models/sahur.glb");

  const mesh = nodes.tung_tung_tung_sahur_Lowpoly_Material002_0 as THREE.Mesh<
    THREE.BufferGeometry,
    THREE.Material | THREE.Material[]
  >;

  const material = materials["Material.002"] as THREE.Material;

  useFrame((_, delta) => {
    if (!groupRef.current) return;

    groupRef.current.rotation.y += delta * 0.8;
  });

  return (
    <group ref={groupRef} dispose={null}>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={mesh.geometry}
          material={material}
          rotation={[-Math.PI / 2, 0, -Math.PI / 3]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/sahur.glb");
